### ISSUE TITLE
feat: support for limits in qdrant config

### ISSUE THREAD

**Issue by konrad-czarnota-ds** [deepsense-ai/ragbits#269]
I would like to provide additional field to qdrant config in the following way:
```
type: ragbits.core.vector_stores.qdrant:QdrantVectorStore
config:
  client:
    type: AsyncQdrantClient
    config:
      limits:
        max_keepalive_connections: 0
        keepalive_expiry: 20
```

The thing is that AsyncQdrantClient expects an object like that:
```
httpx.Limits(max_connections=None, max_keepalive_connections=0, keepalive_expiry=20)
```

So we probably need to adjust QdrantVectorStore:from_config method to convert dict to limits object.

It is necessary for me because I'm getting random connection errors from qdrant related to this keepalive feature and need to adjust them.
